import {
  Activity,
  Sparkles,
  Target,
  TrendingUp,
  Users,
  Zap,
  ArrowRight,
  Clock,
  CheckCircle2,
  PlayCircle,
  AlertCircle,
  FileText,
} from "lucide-react";
import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { Link } from "react-router-dom";
import { PageHeader } from "@/components/PageHeader";
import { StatCard } from "@/components/StatCard";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { cn } from "@/lib/utils";

const revenueData = [
  { name: "Mon", v: 320, b: 210 },
  { name: "Tue", v: 410, b: 240 },
  { name: "Wed", v: 380, b: 290 },
  { name: "Thu", v: 520, b: 310 },
  { name: "Fri", v: 610, b: 380 },
  { name: "Sat", v: 540, b: 320 },
  { name: "Sun", v: 720, b: 410 },
];

const agentRunData = [
  { name: "W1", runs: 42 },
  { name: "W2", runs: 58 },
  { name: "W3", runs: 71 },
  { name: "W4", runs: 64 },
  { name: "W5", runs: 89 },
  { name: "W6", runs: 102 },
];

const agents = [
  { name: "Market Research", status: "running", load: 72, color: "var(--chart-1)" },
  { name: "Competitor Intel", status: "completed", load: 100, color: "var(--chart-2)" },
  { name: "Lead Generator", status: "running", load: 48, color: "var(--chart-3)" },
  { name: "Website Auditor", status: "idle", load: 0, color: "var(--chart-4)" },
  { name: "Opportunity Scorer", status: "completed", load: 100, color: "var(--chart-5)" },
  { name: "Outreach Composer", status: "running", load: 31, color: "var(--chart-1)" },
  { name: "Reporting Engine", status: "idle", load: 0, color: "var(--chart-2)" },
];

const activity = [
  { agent: "Market Research", action: "Completed analysis for Stripe", time: "2m ago", icon: CheckCircle2, tone: "success" },
  { agent: "Lead Generator", action: "Sourced 24 qualified leads in FinTech", time: "11m ago", icon: PlayCircle, tone: "primary" },
  { agent: "Website Auditor", action: "Crawling acme.io — 142/300 pages", time: "24m ago", icon: Activity, tone: "primary" },
  { agent: "Outreach Composer", action: "Generated 12 personalized sequences", time: "1h ago", icon: CheckCircle2, tone: "success" },
  { agent: "Competitor Intel", action: "Rate limit on SimilarWeb, retrying", time: "1h ago", icon: AlertCircle, tone: "warning" },
];

const recentReports = [
  { title: "Q3 FinTech Landscape", type: "Market Research", time: "Today" },
  { title: "Acme vs Initech — Positioning", type: "Competitors", time: "Yesterday" },
  { title: "Top 50 SaaS leads — DACH", type: "Lead Generation", time: "2d ago" },
  { title: "acme.io technical audit", type: "Website Audit", time: "3d ago" },
];

export default function Dashboard() {
  return (
    <>
      <PageHeader
        title="Welcome back, Jordan"
        description="Your seven agents are coordinating on 3 active analyses. Here's what's happening across the workspace."
        actions={
          <>
            <Button variant="outline">Export</Button>
            <Button className="bg-[image:var(--gradient-primary)] text-primary-foreground shadow-[var(--shadow-glow)] hover:opacity-90">
              <Sparkles className="mr-2 h-4 w-4" />
              New analysis
            </Button>
          </>
        }
      />

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard label="Analyses this month" value="248" delta={12.4} icon={Sparkles} helper="vs last 30d" />
        <StatCard label="Qualified leads" value="1,842" delta={8.1} icon={Target} helper="across 4 agents" />
        <StatCard label="Avg opportunity score" value="74.6" delta={-2.3} icon={TrendingUp} helper="last 7 days" />
        <StatCard label="Agents online" value="7 / 7" icon={Zap} helper="all systems nominal" />
      </div>

      <div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-3">
        <div className="surface-card lg:col-span-2 p-6">
          <div className="mb-4 flex items-center justify-between">
            <div>
              <h3 className="text-base font-semibold">Pipeline value</h3>
              <p className="text-xs text-muted-foreground">Estimated pipeline generated by agents</p>
            </div>
            <Badge variant="secondary" className="border-border bg-secondary">Last 7 days</Badge>
          </div>
          <ResponsiveContainer width="100%" height={260}>
            <AreaChart data={revenueData}>
              <defs>
                <linearGradient id="gV" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor="var(--color-chart-1)" stopOpacity={0.4} />
                  <stop offset="100%" stopColor="var(--color-chart-1)" stopOpacity={0} />
                </linearGradient>
                <linearGradient id="gB" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor="var(--color-chart-2)" stopOpacity={0.3} />
                  <stop offset="100%" stopColor="var(--color-chart-2)" stopOpacity={0} />
                </linearGradient>
              </defs>
              <CartesianGrid stroke="var(--color-border)" strokeDasharray="3 3" vertical={false} />
              <XAxis dataKey="name" stroke="var(--color-muted-foreground)" fontSize={11} tickLine={false} axisLine={false} />
              <YAxis stroke="var(--color-muted-foreground)" fontSize={11} tickLine={false} axisLine={false} />
              <Tooltip
                contentStyle={{
                  background: "var(--color-popover)",
                  border: "1px solid var(--color-border)",
                  borderRadius: 12,
                  fontSize: 12,
                }}
              />
              <Area type="monotone" dataKey="v" stroke="var(--color-chart-1)" strokeWidth={2} fill="url(#gV)" />
              <Area type="monotone" dataKey="b" stroke="var(--color-chart-2)" strokeWidth={2} fill="url(#gB)" />
            </AreaChart>
          </ResponsiveContainer>
        </div>

        <div className="surface-card p-6">
          <div className="mb-4 flex items-center justify-between">
            <h3 className="text-base font-semibold">Agent runs</h3>
            <Badge variant="secondary" className="border-border bg-secondary">6 weeks</Badge>
          </div>
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={agentRunData}>
              <CartesianGrid stroke="var(--color-border)" strokeDasharray="3 3" vertical={false} />
              <XAxis dataKey="name" stroke="var(--color-muted-foreground)" fontSize={11} tickLine={false} axisLine={false} />
              <YAxis stroke="var(--color-muted-foreground)" fontSize={11} tickLine={false} axisLine={false} />
              <Tooltip
                contentStyle={{
                  background: "var(--color-popover)",
                  border: "1px solid var(--color-border)",
                  borderRadius: 12,
                  fontSize: 12,
                }}
              />
              <Bar dataKey="runs" fill="var(--color-chart-1)" radius={[6, 6, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-3">
        <div className="surface-card p-6 lg:col-span-2">
          <div className="mb-5 flex items-center justify-between">
            <div>
              <h3 className="text-base font-semibold">AI agent status</h3>
              <p className="text-xs text-muted-foreground">Live load across the multi-agent pipeline</p>
            </div>
            <Link to="/dashboard" className="text-xs text-muted-foreground hover:text-foreground">
              View all
            </Link>
          </div>
          <div className="grid gap-3 sm:grid-cols-2">
            {agents.map((a) => (
              <div
                key={a.name}
                className="group rounded-lg border border-border bg-card/50 p-4 transition-colors hover:border-primary/40"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span
                      className={cn(
                        "h-2 w-2 rounded-full",
                        a.status === "running" && "bg-[oklch(0.78_0.17_155)] animate-pulse",
                        a.status === "completed" && "bg-[oklch(0.72_0.17_195)]",
                        a.status === "idle" && "bg-muted-foreground/40",
                      )}
                    />
                    <span className="text-sm font-medium">{a.name}</span>
                  </div>
                  <span className="text-[10px] uppercase tracking-wider text-muted-foreground">
                    {a.status}
                  </span>
                </div>
                <Progress value={a.load} className="mt-3 h-1.5" />
              </div>
            ))}
          </div>
        </div>

        <div className="surface-card p-6">
          <div className="mb-5 flex items-center justify-between">
            <h3 className="text-base font-semibold">Activity</h3>
            <Clock className="h-4 w-4 text-muted-foreground" />
          </div>
          <ul className="space-y-4">
            {activity.map((a, i) => (
              <li key={i} className="flex gap-3">
                <div
                  className={cn(
                    "mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-md border border-border",
                    a.tone === "success" && "text-[oklch(0.78_0.17_155)]",
                    a.tone === "primary" && "text-primary",
                    a.tone === "warning" && "text-[oklch(0.78_0.16_75)]",
                  )}
                >
                  <a.icon className="h-3.5 w-3.5" />
                </div>
                <div className="min-w-0 flex-1">
                  <p className="text-sm">
                    <span className="font-medium">{a.agent}</span>{" "}
                    <span className="text-muted-foreground">— {a.action}</span>
                  </p>
                  <p className="text-xs text-muted-foreground">{a.time}</p>
                </div>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-3">
        <div className="surface-card p-6 lg:col-span-2">
          <div className="mb-5 flex items-center justify-between">
            <h3 className="text-base font-semibold">Recent reports</h3>
            <Link to="/reports" className="inline-flex items-center text-xs text-muted-foreground hover:text-foreground">
              All reports <ArrowRight className="ml-1 h-3 w-3" />
            </Link>
          </div>
          <div className="divide-y divide-border">
            {recentReports.map((r) => (
              <div key={r.title} className="flex items-center justify-between py-3 first:pt-0 last:pb-0">
                <div className="flex items-center gap-3">
                  <div className="flex h-9 w-9 items-center justify-center rounded-md border border-border bg-card">
                    <FileText className="h-4 w-4 text-muted-foreground" />
                  </div>
                  <div>
                    <p className="text-sm font-medium">{r.title}</p>
                    <p className="text-xs text-muted-foreground">{r.type}</p>
                  </div>
                </div>
                <span className="text-xs text-muted-foreground">{r.time}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="surface-card p-6">
          <h3 className="text-base font-semibold">Quick actions</h3>
          <p className="mt-1 text-xs text-muted-foreground">Spin up an agent in one click.</p>
          <div className="mt-4 space-y-2">
            {[
              { to: "/market-research", label: "Run market research", icon: Sparkles },
              { to: "/leads", label: "Generate new leads", icon: Target },
              { to: "/website-audit", label: "Audit a website", icon: Activity },
              { to: "/outreach", label: "Draft outreach", icon: Users },
            ].map((q) => (
              <Link
                key={q.to}
                to={q.to}
                className="flex items-center justify-between rounded-lg border border-border bg-card/50 px-3 py-2.5 text-sm transition-colors hover:border-primary/40 hover:bg-card"
              >
                <span className="flex items-center gap-2">
                  <q.icon className="h-4 w-4 text-muted-foreground" />
                  {q.label}
                </span>
                <ArrowRight className="h-3.5 w-3.5 text-muted-foreground" />
              </Link>
            ))}
          </div>
        </div>
      </div>
    </>
  );
}
