import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Download, Trash2, Search, FileText } from "lucide-react";
import { PageHeader } from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

const seed = [
  { id: "r-001", title: "Q3 FinTech Landscape", type: "Market Research", createdAt: "Jun 24, 2026", size: "1.4 MB" },
  { id: "r-002", title: "Acme vs Initech — Positioning", type: "Competitors", createdAt: "Jun 22, 2026", size: "820 KB" },
  { id: "r-003", title: "Top 50 SaaS leads — DACH", type: "Lead Generation", createdAt: "Jun 19, 2026", size: "412 KB" },
  { id: "r-004", title: "acme.io technical audit", type: "Website Audit", createdAt: "Jun 14, 2026", size: "2.1 MB" },
  { id: "r-005", title: "Opportunity scoring — Q3", type: "Opportunities", createdAt: "Jun 11, 2026", size: "780 KB" },
  { id: "r-006", title: "Outreach kit — HealthTech CIOs", type: "Outreach", createdAt: "Jun 02, 2026", size: "330 KB" },
];

export default function Reports() {
  const [q, setQ] = useState("");
  const [items, setItems] = useState(seed);

  const filtered = useMemo(
    () =>
      items.filter(
        (r) => !q || r.title.toLowerCase().includes(q.toLowerCase()) || r.type.toLowerCase().includes(q.toLowerCase()),
      ),
    [items, q],
  );

  return (
    <>
      <PageHeader
        title="Reports"
        description="PDF exports generated by your agents. Searchable, downloadable, deletable."
      />

      <div className="surface-card p-5">
        <div className="relative max-w-md">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search reports" className="pl-9" />
        </div>

        <div className="mt-5 overflow-hidden rounded-lg border border-border">
          <Table>
            <TableHeader>
              <TableRow className="border-border hover:bg-transparent">
                <TableHead>Report</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Created</TableHead>
                <TableHead>Size</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filtered.length === 0 ? (
                <TableRow className="border-border hover:bg-transparent">
                  <TableCell colSpan={5} className="py-12 text-center text-sm text-muted-foreground">
                    No reports found.
                  </TableCell>
                </TableRow>
              ) : (
                filtered.map((r) => (
                  <TableRow key={r.id} className="border-border">
                    <TableCell>
                      <div className="flex items-center gap-3">
                        <div className="flex h-9 w-9 items-center justify-center rounded-md border border-border bg-card">
                          <FileText className="h-4 w-4 text-muted-foreground" />
                        </div>
                        <span className="font-medium">{r.title}</span>
                      </div>
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline" className="border-border">{r.type}</Badge>
                    </TableCell>
                    <TableCell className="text-muted-foreground">{r.createdAt}</TableCell>
                    <TableCell className="text-muted-foreground">{r.size}</TableCell>
                    <TableCell className="text-right">
                      <div className="inline-flex gap-1">
                        <Button size="sm" variant="ghost" onClick={() => toast.success(`Downloading ${r.title}`)}>
                          <Download className="h-4 w-4" />
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => {
                            setItems((prev) => prev.filter((x) => x.id !== r.id));
                            toast.success(`Deleted ${r.title}`);
                          }}
                        >
                          <Trash2 className="h-4 w-4 text-destructive" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>
      </div>
    </>
  );
}
